future: true

collections:
  announcements:
    output: true
  events:
    output: true
  staffs:
    output: true


defaults:
  - scope:
      path: ""
      type: "announcements"
    values:
      layout: "announcement"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "staffs"
    values:
      layout: "staff"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag